amcl:
  ros__parameters:
    use_sim_time: true

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"

    scan_topic: "scan"
    laser_model_type: "likelihood_field"

    min_particles: 500
    max_particles: 2000
    pf_err: 0.05
    pf_z: 0.99

    update_min_d: 0.20
    update_min_a: 0.20
    resample_interval: 1
    transform_tolerance: 1.0

    laser_min_range: 0.10
    laser_max_range: 1.5
    laser_max_beams: 60
    laser_z_hit: 0.5
    laser_z_short: 0.05
    laser_z_max: 0.05
    laser_z_rand: 0.5
    laser_sigma_hit: 0.2
    laser_lambda_short: 0.1

    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.3
    beam_skip_error_threshold: 0.9

    set_initial_pose: false
    always_reset_initial_pose: false
    first_map_only: false
    save_pose_rate: 0.5

    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1

    tf_broadcast: true
    tf_broadcast_period: 0.05
    introspection_mode: "disabled"

    robot_model_type: "nav2_amcl::DifferentialMotionModel"
